Add facebook authentication with passport-facebook.
It doesn't work right now. Getting error.
FacebookTokenError: This authorization code has
been used.